name: CourseArchive
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo I am alive!!!!
      - name: Call our API route
        run: |
          curl --request POST \
          --url 'https://cinemed-agility.vercel.app/api/course-sync' \
          --header 'Authorization: Bearer ${{ secrets.COURSE_ARCHIVATION_TOKEN }}'
