name: 15-minute-cron
on:
  schedule:
    - cron: '*/1 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request POST \
          --url 'https://cinemed-agility.vercel.app/api/course-sync' \
          --header 'Authorization: Bearer ${{ secrets.COURSE_ARCHIVATION_TOKEN }}'
